### ISSUE TITLE
Specification of transport protocol bindings

### ISSUE THREAD

**Issue by sophokles73** [eclipse-uprotocol/uprotocol-spec#15]
I appreciate the latest additions to the spec made in #14 :+1: 

While reading through the [uTransport's Send() definition](https://github.com/eclipse-uprotocol/uprotocol-spec/tree/main/up-l1#22-send) I was wondering, if the proposed way of letting implementations decide if and how to map payload, attributes and URI to the underlying transport's messaging primitives will actually provide for the required interoperability.

Let's assume the mentioned *HartleyTransport* protocol existed and it would provide means to send messages that contain a byte array as payload and would also allow to set generic string based attributes on a message.

The first one to implement the uTransport for HartleyTransport in Java will now decide, how the URI and attributes passed in to the Send() method will be mapped to HartleyTransport message attributes.

Several months later, I want to implement the uTranport for HartleyTransport in my fantasy programming language BUMLUX. How do I find out, which attributes of a HartleyTransport message contain the URI and the message properties provided by the original sender?

If the sender of the message used the Java implementation, then I will need to dig into the Java code to find out where the information is to be found in the message. However, what if somebody else had implemented a Python based implementation of the HartleyTransport and has mapped the attributes differently, e.g. using a certain attribute name prefix?

I guess what I am saying is that IMHO we need transport protocol specific *bindings* for the message payload, attributes and URI instead of leaving this up to the (first/each?) implementer of a transport. We might be able to simply refer to the existing CloudEvent bindings for obvious transport protocols and add our own bindings for more exotic protocols like Zenoh.

WDYT?

**Comment by stevenhartley** [comment]
Hi @sophokles73 ,
Justifications and shortfalls of CloudEvents as __the__ only message format (with different protocol bindings) was documented in https://github.com/eclipse-uprotocol/uprotocol-spec/issues/13. 

About your specific question vs UPayload; Trust me we've been decerning over this very topic for 2 years! There are two answers to the million dollar question, the encoding format for the payload and the schema (what is where inside of the payload. UAttributes stores the uProtocol metadata for routing and UPayload metadata where the transport **MUST NOT** touch or change the payload.

1. **Schema:**  Simply put, the schema can be assumed based on the topic (UUri). We use to pass dataschema attribute but found it always redundant, especially since UResource contained the Message (for topics) or for methods, you cannot change the messages in methods without breaking protobuf rules.
2. **Encoding (a.k.a USerializartionHint):** A general rule of thumb we are firm on is your sender **MUST** send data in a format that receiver knows how to receive it. By this I mean the platform (and dispatchers) **MUST NEVER** transcode or touch the payload, as doing so opens up way to many cans of worms that will take many German beers to explain. So If the sender and receivers are on the same transport (i.e. a zero copy, shared memory based transport) they can share pointers to structures (assuming everyone is coded in rust/c++/C). If the sender and receivers span different languages and transports, you have no choice but to either put some other uE in the middle (who can aggregate/transcode) or encode the payload in a format that is portable across languages and environments (i.e. protobuf)

**Comment by sophokles73** [comment]
I believe that we can agree on transports MUST NOT touch nor change the payload.
Apart from that, I am not sure if what you wrote is actually an answer to my question.

Let's try to use an example:

Say I have a byte array (UPayload) that I want to send to a service endpoint (identified by a UUri) and also some metadata that I want to include (a set of UAttributes). Let's also assume that my sender is implemented in Rust and I want to use MQTT 3.1.1 as the transport protocol.

My understanding is that someone first needs to implement the uTransport interface for MQTT in Rust, so that I can actually send the message. Given that MQTT 3.1.1 does not provide means to add metadata to a message, the attributes (and UUri) need to be encoded in an envelope together with the (unchanged) payload data and be serialized to the MQTT message body. Up until now, my understanding was that you explicitly defined Cloud Events to be this envelope format (taking advantage of the Cloud Event MQTT binding).

With that definition gone, my understanding now is that I as the implementer of the uTransport can basically do whatever I want to encode the information into the MQTT message. That is fine, but raises the question how an implementer of a Python based MQTT 3.1.1 uTransport would know, how to the read and decode the information from the MQTT message that I have sent?

> A general rule of thumb we are firm on is your sender MUST send data in a format that receiver knows how to receive it.

Does this mean that you do not anticipate (nor explicitly want to support) multiple parties being able to implement the sender and receiver side uTransports independently from each other? Because for that to happen, IMHO we would need to explicitly define how UUid, UAttributes and UPayload should be mapped to a given transport protocol.

**Comment by sophokles73** [comment]
>  that is why there are transport specific specifications that mandate the the message format

That is what I was referring to as well :-) My understanding of your latest changes to the uTransport interface was that you no longer want to prescribe how the information given needs to be mapped to the underlying transport's messaging constructs. I am glad to hear that I was mistaken :+1:

**Comment by stevenhartley** [comment]
Closing the issue based on last comment
